//import Head from "next/head";
import Head from "next/head";
import About from "../components/About";
import Main from "../components/main";
import Navbar from "../components/Navbar";
import Skills from "../components/Skills";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Mahi | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Main/>
      <About/>
      <Skills/>
    </div>
  );
}
